name: Sovrn Auto Poster

on:
  # Se ejecuta cada 6 horas
  schedule:
    - cron: '0 */6 * * *'
  # Permite ejecutarlo manualmente con un botón desde GitHub
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar Bot
        env:
          # AQUI ESTABA EL ERROR: El nombre de la izquierda debe coincidir con lo que busca Python
          # El nombre de la derecha debe coincidir con tu Secreto en GitHub
          CREDENCIALES: ${{ secrets.CREDENCIALES }}
        run: python bot_sheet_final.py
